### ISSUE TITLE
Faltan algunos ficheros

### ISSUE THREAD

**Issue by rmartinsanta** [pc1b/DuckBit#30]
En la rama `part3` faltan algunos ficheros necesarios que busca la aplicación al arrancar, es posible que existan en local, pero que no estén en el repositorio de Github.

Ejemplos:
- src/main/resources/static/images/logo.jpg
- src/main/resources/static/images/admin.jpg
- src/main/resources/static/leaks/{1,2,3}.txt

Comprobad que la aplicación arranca partiendo de un clon de la rama.

**Comment by pc1b** [comment]
Las imágenes que mencionas si que están en el repositorio:
https://github.com/pc1b/DuckBit/blob/part3/DuckBit/src/main/resources/static/images/admin.jpg
https://github.com/pc1b/DuckBit/blob/part3/DuckBit/src/main/resources/static/images/logo.jpg

Y los leaks ya no se encuentran en esa ruta, me temo que te has clonado otra rama... Estamos trabajando sobre la rama `part3`, el resto de ramas pueden estar desactualizadas.

**Comment by rmartinsanta** [comment]
Toda la razón, estaba usando la rama main en vez de la rama de la tercera parte.

En la rama `part3` funciona perfectamente.
