### ISSUE TITLE
Referential Integrity (N:M)

### ISSUE THREAD

**Issue by rmartinsanta** [pc1b/DuckBit#31]
He intentado replicar el fallo que vimos ayer y no lo he conseguido, me funciona perfectamente. Una posibilidad es que tengáis la base de datos con datos que Spring no ha eliminado / alguna inconsistencia y por eso no funciona como debería.

Yo probaría desde una consola de MySQL o el Workbench a borrar la base de datos entera y volverla a crear antes de arrancar la aplicación, es posible que empiece a funcionar sin cambiar el código.

Si sigue igual, avisad y revisamos en más detalle

**Comment by rmartinsanta** [comment]
Si os sigue pasando tras limpiar la BBDD, dad una lista de pasos para reproducir el error. Ejemplo:
1. Crear una base de datos que se llame XYZ
2. Configurar la base de datos en el application.properties y arrancar la aplicación
3. Hacer XYZ petición a la API, debería fallar, y el resultado esperado es XYZ.

**Comment by pc1b** [comment]
En este caso creo que ha pasado lo mismo que con el anterior. En las versiones anteriores, se eliminaban manualmente las relaciones sin hacer un correcto uso del `cascade`. Funcionaba, pero creo que no es del todo correcto.
En la versión actual, basta con arrancar una BBDD `duckbit` con un motor mysql 8.0.33:
```
docker run --rm -e MYSQL_ROOT_PASSWORD=password -e MYSQL_DATABASE=duckbit -p 3306:3306 -d mysql:8.0.33
```
Arrancar la aplicación con el application.propierties que esta subido al repositorio y desde la API hacer una petición delete el endpoint `/api/combo/1`. Produce la excepción:
```
java.sql.SQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`duckbit`.`leak_combos`, CONSTRAINT `FKgfigx4wukgg7hem8wckcp9nle` FOREIGN KEY (`combos_id`) REFERENCES `combo` (`id`))
```
En el panel de administración de la web también se pueden eliminar combos, produciendo el mismo error.

**Comment by rmartinsanta** [comment]
Toda la razón, estaba usando la rama main en vez de la rama de la tercera parte.
Cierro porque ya está solucionado el problema.
